version: "3"

services:     
  geolocation-app:
    container_name: geolocation-app
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"