version: "3"

services:     
  geolocation-app:
    container_name: geolocation-app
    environment:
      API_TOKEN: 'PLACEHOLDER'
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/app
    ports:
      - "80:80"