# Generated by Django 3.2.6 on 2021-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
