# Generated by Django 3.2.6 on 2021-09-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_alter_geolocation_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
